#!/usr/bin/env python3
"""Regenerate src/blind-topics.ts from the app's Shared/SoloPractice.swift Blind Ranking bank.

Usage: python3 scripts/sync-blind-topics.py /path/to/imessage-sports-games/Shared/SoloPractice.swift
Re-run and redeploy whenever Blind Ranking topics change in the app.
"""
import json, re, sys

src = open(sys.argv[1]).read()
start = src.index("static let blinds: [BlindPrompt] = [")
end = src.index("\n    ]\n", start)
block = src[start:end]
topics = {}
for chunk in block.split("BlindPrompt(")[1:]:
    tid = re.search(r'id:\s*"([^"]+)"', chunk).group(1)
    items = re.findall(r'GameItem\(id:\s*"([^"]+)"', chunk)
    assert len(items) == 5 and len(set(items)) == 5, tid
    topics[tid] = items
assert len(topics) >= 30
out = "// Generated by scripts/sync-blind-topics.py from the app's Blind Ranking bank. Do not edit.\n"
out += "export const BLIND_TOPICS: Record<string, readonly string[]> = " + json.dumps(topics, indent="\t") + ";\n"
open("src/blind-topics.ts", "w").write(out)
print(f"{len(topics)} topics")
