// Generated by scripts/sync-blind-topics.py from the app's Blind Ranking bank. Do not edit.
export const BLIND_TOPICS: Record<string, readonly string[]> = {
	"blind-cfb-heisman-2000s": [
		"tim-tebow",
		"cam-newton",
		"johnny-manziel",
		"lamar-jackson",
		"joe-burrow"
	],
	"blind-nfl-multi-mvp": [
		"peyton-manning",
		"aaron-rodgers",
		"tom-brady",
		"patrick-mahomes",
		"lamar-jackson"
	],
	"blind-nba-multi-mvp": [
		"michael-jordan",
		"lebron-james",
		"kareem-abdul-jabbar",
		"larry-bird",
		"nikola-jokic"
	],
	"blind-nba-dynasties": [
		"bill-russell-s-celtics",
		"showtime-lakers",
		"jordan-s-bulls",
		"duncan-s-spurs",
		"curry-s-warriors"
	],
	"blind-nfl-dynasties": [
		"lombardi-s-packers",
		"1970s-steelers",
		"1980s-49ers",
		"1990s-cowboys",
		"brady-belichick-patriots"
	],
	"blind-nfl-qb-duos": [
		"montana-rice",
		"manning-harrison",
		"brady-gronkowski",
		"mahomes-kelce",
		"aikman-irvin"
	],
	"blind-nfl-rookie-qbs": [
		"robert-griffin-iii-2012",
		"dak-prescott-2016",
		"justin-herbert-2020",
		"c-j-stroud-2023",
		"jayden-daniels-2024"
	],
	"blind-nfl-rbs-2000s": [
		"ladainian-tomlinson",
		"adrian-peterson",
		"shaun-alexander",
		"edgerrin-james",
		"priest-holmes"
	],
	"blind-nfl-sb-mvps": [
		"steve-young-xxix",
		"jerry-rice-xxiii",
		"doug-williams-xxii",
		"joe-montana-xxiv",
		"tom-brady-li"
	],
	"blind-nfl-sb-coaches": [
		"bill-belichick",
		"vince-lombardi",
		"don-shula",
		"bill-walsh",
		"andy-reid"
	],
	"blind-nfl-sb-upsets": [
		"jets-over-colts-iii",
		"chiefs-over-vikings-iv",
		"patriots-over-rams-xxxvi",
		"giants-over-18-0-patriots-xlii",
		"eagles-over-patriots-lii"
	],
	"blind-nfl-multi-dpoy": [
		"lawrence-taylor",
		"j-j-watt",
		"aaron-donald",
		"reggie-white",
		"bruce-smith"
	],
	"blind-nba-finals-mvps": [
		"shaquille-o-neal",
		"lebron-james",
		"kobe-bryant",
		"kawhi-leonard",
		"stephen-curry"
	],
	"blind-nba-big-threes": [
		"bird-mchale-parish",
		"jordan-pippen-rodman",
		"duncan-parker-ginobili",
		"lebron-wade-bosh",
		"curry-thompson-green"
	],
	"blind-nba-single-season": [
		"1985-86-celtics",
		"1986-87-lakers",
		"1995-96-bulls",
		"2000-01-lakers",
		"2016-17-warriors"
	],
	"blind-nba-top-picks": [
		"lebron-james",
		"dwight-howard",
		"derrick-rose",
		"anthony-davis",
		"victor-wembanyama"
	],
	"blind-nba-ringless": [
		"karl-malone",
		"charles-barkley",
		"allen-iverson",
		"patrick-ewing",
		"carmelo-anthony"
	],
	"blind-nba-roy": [
		"lebron-james",
		"chris-paul",
		"kevin-durant",
		"damian-lillard",
		"luka-doncic"
	],
	"blind-nba-dunk-champs": [
		"dominique-wilkins",
		"michael-jordan",
		"vince-carter",
		"zach-lavine",
		"mac-mcclung"
	],
	"blind-mlb-multi-mvp": [
		"barry-bonds",
		"mickey-mantle",
		"albert-pujols",
		"mike-trout",
		"shohei-ohtani"
	],
	"blind-mlb-dynasties": [
		"1949-53-yankees",
		"1972-74-athletics",
		"1975-76-reds",
		"1996-2000-yankees",
		"2010s-giants"
	],
	"blind-mlb-cy-young": [
		"pedro-martinez",
		"randy-johnson",
		"clayton-kershaw",
		"justin-verlander",
		"jacob-degrom"
	],
	"blind-mlb-sluggers-2000s": [
		"barry-bonds",
		"albert-pujols",
		"alex-rodriguez",
		"manny-ramirez",
		"david-ortiz"
	],
	"blind-mlb-october-moments": [
		"mazeroski-s-1960-walk-off",
		"gibson-s-1988-homer",
		"carter-s-1993-walk-off",
		"boone-s-2003-pennant-homer",
		"freese-s-2011-game-6"
	],
	"blind-cfb-dynasties": [
		"bud-wilkinson-s-oklahoma",
		"1980s-miami",
		"tom-osborne-s-nebraska",
		"nick-saban-s-alabama",
		"dabo-swinney-s-clemson"
	],
	"blind-cfb-teams-2000s": [
		"2001-miami",
		"2005-texas",
		"2013-florida-state",
		"2019-lsu",
		"2020-alabama"
	],
	"blind-cfb-no-heisman-qbs": [
		"peyton-manning",
		"vince-young",
		"andrew-luck",
		"deshaun-watson",
		"tua-tagovailoa"
	],
	"blind-cfb-rivalries": [
		"ohio-state-vs-michigan",
		"alabama-vs-auburn",
		"texas-vs-oklahoma",
		"army-vs-navy",
		"notre-dame-vs-usc"
	],
	"blind-cbb-coaches": [
		"john-wooden",
		"mike-krzyzewski",
		"dean-smith",
		"bob-knight",
		"jim-calhoun"
	],
	"blind-cbb-buzzer-beaters": [
		"lorenzo-charles-1983",
		"christian-laettner-1992",
		"tyus-edney-1995",
		"kris-jenkins-2016",
		"jalen-suggs-2021"
	],
	"blind-cbb-one-and-done": [
		"carmelo-anthony",
		"kevin-durant",
		"derrick-rose",
		"anthony-davis",
		"zion-williamson"
	],
	"blind-nhl-multi-hart": [
		"wayne-gretzky",
		"bobby-orr",
		"mario-lemieux",
		"alex-ovechkin",
		"connor-mcdavid"
	],
	"blind-soccer-ballon-dor": [
		"lionel-messi",
		"cristiano-ronaldo",
		"ronaldinho",
		"kaka",
		"luka-modric"
	]
};
